artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://drive.google.com/uc?id=1ve70rcYzzopIqBKiZ1EMN65JobT4XcwO"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : "artifacts/data_ingestion"
  


model_trainer:
  root_dir : artifacts/model_trainer
  alignment_data_path : artifacts/data_ingestion/data/alignments/s1
  speaker_data_path : artifacts/data_ingestion/data/s1
  landmark_model_path : artifacts/data_ingestion/data/landmark_model/face_landmarker.task

